# Generated by Django 5.2.3 on 2025-06-25 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instituicao', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Cargo')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Patente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Patente')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Usado para ordenar por hierarquia')),
            ],
            options={
                'verbose_name': 'Patente',
                'verbose_name_plural': 'Patentes',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_vinculo', models.CharField(choices=[('SV', 'Sem Vínculo'), ('PE', 'Pendente'), ('AT', 'Ativo'), ('RJ', 'Rejeitado')], default='SV', max_length=2, verbose_name='Status do Vínculo')),
                ('is_admin_instituicao', models.BooleanField(default=False, verbose_name='É Administrador da Instituição')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF')),
                ('celular', models.CharField(blank=True, max_length=15, null=True, verbose_name='Celular')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='profile_photos/', verbose_name='Foto do Perfil')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação do Perfil')),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.cargo', verbose_name='Cargo')),
                ('instituicao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='instituicao.instituicao', verbose_name='Instituição Vinculada')),
                ('patente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.patente', verbose_name='Patente')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuários',
                'ordering': ['user__username'],
            },
        ),
    ]
