# Generated by Django 5.2.3 on 2025-06-24 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(blank=True, help_text='Exemplo: Guarda, Supervisor, Administrador', max_length=100, null=True, verbose_name='Cargo')),
                ('instituicao', models.CharField(blank=True, help_text='Nome da instituição associada, ex.: Guarda Civil Municipal', max_length=200, null=True, verbose_name='Instituição')),
                ('cidade_uf', models.CharField(blank=True, help_text='Exemplo: Guaira - SP', max_length=100, null=True, verbose_name='Cidade - UF')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF')),
                ('celular', models.CharField(blank=True, max_length=15, null=True, verbose_name='Celular')),
                ('fone', models.CharField(blank=True, max_length=14, null=True, verbose_name='Telefone')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='profile_photos/', verbose_name='Foto do Usuário')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuários',
                'ordering': ['user__username'],
                'permissions': [('can_add_userprofile', 'Can add user profile'), ('can_change_userprofile', 'Can change user profile'), ('can_delete_userprofile', 'Can delete user profile')],
            },
        ),
    ]
