# Generated by Django 5.2.3 on 2025-06-22 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['user__username'], 'permissions': [('can_add_userprofile', 'Can add user profile'), ('can_change_userprofile', 'Can change user profile'), ('can_delete_userprofile', 'Can delete user profile')], 'verbose_name': 'Perfil de Usuário', 'verbose_name_plural': 'Perfis de Usuários'},
        ),
    ]
