# Generated by Django 5.2.3 on 2025-06-22 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_userprofile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='celular',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Celular'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cidade_uf',
            field=models.CharField(blank=True, help_text='Exemplo: Guaira - SP', max_length=100, null=True, verbose_name='Cidade - UF'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fone',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/', verbose_name='Foto do Usuário'),
        ),
    ]
