# Generated by Django 5.2.3 on 2025-06-23 17:54

import instituicao.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Guarda Civil Municipal, Polícia Militar', max_length=200, verbose_name='Nome da Instituição')),
                ('municipio', models.CharField(max_length=100, verbose_name='Município')),
                ('uf', models.CharField(help_text='Ex: SP, RJ', max_length=2, verbose_name='UF')),
                ('cnpj', models.CharField(blank=True, help_text='Formato: 00.000.000/0001-00', max_length=18, null=True, verbose_name='CNPJ')),
                ('contato', models.CharField(blank=True, help_text='Nome do responsável ou telefone', max_length=100, null=True, verbose_name='Contato')),
                ('plano_contratado', models.CharField(blank=True, max_length=50, null=True, verbose_name='Plano Contratado')),
                ('brasao_instituicao', models.ImageField(blank=True, null=True, upload_to=instituicao.models.get_upload_path, verbose_name='Brasão da Instituição')),
                ('brasao_municipio', models.ImageField(blank=True, null=True, upload_to=instituicao.models.get_upload_path, verbose_name='Brasão do Município')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
            ],
            options={
                'verbose_name': 'Instituição',
                'verbose_name_plural': 'Instituições',
                'ordering': ['nome', 'municipio'],
            },
        ),
    ]
