# Generated by Django 5.2.3 on 2025-06-24 13:42

import django.db.models.deletion
import instituicao.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('uf', models.CharField(max_length=2, unique=True, verbose_name='UF')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoInstituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True, verbose_name='Nome do Tipo de Instituição')),
            ],
            options={
                'verbose_name': 'Tipo de Instituição',
                'verbose_name_plural': 'Tipos de Instituições',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipios', to='instituicao.estado')),
            ],
            options={
                'verbose_name': 'Município',
                'verbose_name_plural': 'Municípios',
                'ordering': ['nome'],
                'unique_together': {('estado', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_gerado', models.CharField(editable=False, max_length=255, null=True, verbose_name='Nome Gerado')),
                ('cnpj', models.CharField(blank=True, help_text='Formato: 00.000.000/0001-00', max_length=18, null=True, unique=True, verbose_name='CNPJ')),
                ('contato', models.CharField(blank=True, help_text='Nome do responsável ou telefone', max_length=100, null=True, verbose_name='Contato')),
                ('email_institucional', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail Institucional')),
                ('plano_contratado', models.CharField(blank=True, max_length=50, null=True, verbose_name='Plano Contratado')),
                ('brasao_instituicao', models.ImageField(blank=True, null=True, upload_to=instituicao.models.get_upload_path, verbose_name='Brasão da Instituição')),
                ('brasao_municipio', models.ImageField(blank=True, null=True, upload_to=instituicao.models.get_upload_path, verbose_name='Brasão do Município')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='instituicao.municipio', verbose_name='Município')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='instituicao.tipoinstituicao', verbose_name='Tipo de Instituição')),
            ],
            options={
                'verbose_name': 'Instituição',
                'verbose_name_plural': 'Instituições',
                'ordering': ['nome_gerado'],
                'unique_together': {('tipo', 'municipio')},
            },
        ),
    ]
