# Generated by Django 5.2.3 on 2025-06-23 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituicao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoInstituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True, verbose_name='Nome do Tipo de Instituição')),
            ],
            options={
                'verbose_name': 'Tipo de Instituição',
                'verbose_name_plural': 'Tipos de Instituições',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='instituicao',
            options={'ordering': ['tipo__nome', 'municipio'], 'verbose_name': 'Instituição', 'verbose_name_plural': 'Instituições'},
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='cnpj',
            field=models.CharField(blank=True, help_text='Formato: 00.000.000/0001-00', max_length=18, null=True, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AddField(
            model_name='instituicao',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='instituicao.tipoinstituicao', verbose_name='Tipo de Instituição'),
        ),
        migrations.AlterUniqueTogether(
            name='instituicao',
            unique_together={('tipo', 'municipio', 'uf')},
        ),
        migrations.RemoveField(
            model_name='instituicao',
            name='nome',
        ),
    ]
